### ISSUE TITLE
Web UI is not exposed

### ISSUE THREAD

**Issue by paularmstrong** [hassio-addons/addon-jupyterlab-lite#181]
# Problem/Motivation

Cannot access the application

## Expected behavior

Install the application. Ensure it has started correctly.
Click "Open Web UI"
Expect to see the web UI inside the Home Assistant UI

## Actual behavior

Get opened a new window/tab with `https://my-home-assistant-domain.example.com:7777` (example domain). Obviously I have not yet opened that port and I do not intend to open that port to the world.

Attempt to access `hassio.local:7777`, but receive a HTTP Basic Auth prompt, but no instructions are given for the username/password.

## Steps to reproduce

Follow the instructions in the README for this repository

```yaml
github_access_token: '!secret github_token'
ssl: false
certfile: fullchain.pem
keyfile: privkey.pem
system_packages: []
init_commands: []
```

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)
